### ISSUE TITLE
Require a param for the interpreter in my python virtual environemt.

### ISSUE THREAD

**Issue by alanthssss** [chialiyun/DiagramsPreviewerVSCExt#5]
Hey, Nice to implement the preview via your kind extension!

I installed `diagrams` dependcies on my virtual environment instead of pure python3 environment, and I generated diagrams successfully.
Then when I used this cool extension to preview my diagrams, it said my python3 env does not have `diagrams`.

I guess here I need a blank to fill the location of the virtual envitonment's interpreter instead of only 3 choices: default, python, python3, or read the interpreter which is being used by `Microsoft VS Code Python Extension`.

Feel free to tell me whether my descriptions are clear enough.

Cheers!

**Comment by msouff** [comment]
+1 to env support.

**Comment by chialiyun** [comment]
Hi @alanthssss and @msouff, thank you so much for trying out the extension. Appreciate the feedback on the use case on using the interpreter that is set from vscode python extension.

We would like to share with you a good news - we are in the mist of adding this capability.
We will keep you posted once it’s ready. 😃

**Comment by chialiyun** [comment]
Hi @alanthssss and @msouff 

We have released a new version (1.0.6) to cater for this functionality. 🤟 

You may try out the new option in the settings - "VS Code Python Interpreter"
<img width="513" alt="image" src="https://user-images.githubusercontent.com/15521388/196177074-c409b820-b5fe-4ead-82ed-45ce3badeb85.png">

Feel free to reach out again for any other issues. 😸 Cheers 🥂

**Comment by don-harden** [comment]
Hi, thanks for writing this extension.   I am working on a Mac with Python 3.10 and GraphViz installed via brew.  I am trying to run your demo code in a virtual environment.   From the command line (.venv) it works as expected. The png is created and the image viewer opens when show=True.   However in VS Code I get this error no matter what diagramspreviewer.pythonCommand is set to:

![image](https://user-images.githubusercontent.com/23099505/202044655-878868a1-d866-46a1-8b02-40955b728770.png)

VS Code Python interpreter is set to the virtual environment:
![image](https://user-images.githubusercontent.com/23099505/202044744-8afc7fd2-4a56-43f9-9ab7-d7ad354da4fc.png)

And Diagramspreviewer: Python Command is set to "VS Code Python Interpreter"
![image](https://user-images.githubusercontent.com/23099505/202044824-03c9bbff-7a91-468a-969b-445b0ad126fc.png)

Any ideas what I am doing wrong or should try next?

Thanks,
Don

**Comment by chialiyun** [comment]
Hi @don-harden
Thank you for sharing this. 😄 

Would you mind helping me with the following?
1. double check that your are using the latest extension version (`v1.0.6`)? 
2. what's the command that you are run locally? 
3. is your virtual environment in the same directory like in the screenshot below? or would you mind sharing what set up did you had for your virtual environment so that I could try to replicate the same on my side to test it out. 
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/15521388/202155618-8500506b-8298-435c-bbb5-49d3fccf55cc.png">

**Comment by don-harden** [comment]
Hi Chialiyun,  
I installed Diagrams Previewer yesterday and it is version 1.0.6

![image](https://user-images.githubusercontent.com/23099505/202201894-62c51c9a-222c-47b2-b7dc-7905843fddb8.png)

The local command I am running is `python demo.py`   in my Python 3.10 virtual environment.   In the screenshot below you can see that both python and python3 are pointing the virtual environment, and the00 `my_diagram.png` is created when running `python demo.py`
![image](https://user-images.githubusercontent.com/23099505/202205240-84cbb509-dd1a-4663-b309-ff5f020fd404.png)

My virtual environment is in the same directory as your demo code. 
![image](https://user-images.githubusercontent.com/23099505/202206764-0b5452de-b5db-4949-ac65-b62967e74cbe.png)

 Also, since I have show=True the image viewer pops up:
<img width="281" alt="image" src="https://user-images.githubusercontent.com/23099505/202206085-f7788c87-ed25-4b49-8483-abce29cd097e.png">

**Comment by chialiyun** [comment]
hi @don-harden 
Thank for so much for sharing those information. 

It's an issue with how we are reading the script. We will try to fix it ASAP.

In the meantime, if you make line 7-9 into 1 liner, it should work. 
```
with Diagram('Web Service', show=False, filename="my_diagram"):
```

Our apologies on this, please bear with us on this formatting issue. Please let us know again if it still does not work for you.

**Comment by don-harden** [comment]
Yep, it works!  Thanks so much Chialiyun.

![image](https://user-images.githubusercontent.com/23099505/202223644-38d002ff-af07-486a-9e15-c96c90d2109e.png)

**Comment by alanthssss** [comment]
Nice code, and I need to close this issue.
Thx for all your works @msouff @chialiyun @don-harden .

**Comment by chialiyun** [comment]
hi @don-harden 👋 , we are supporting multi-liner `with Diagram` implementation (i.e. if you revert to your original code on line 7-9, the extension should work as well) on `v1.0.7`. Feel free to check it out and reach out again if you encounter any issues. 😄

**Comment by alanthssss** [comment]
@chialiyun Thanks for your great work.
I am using this extension for the diagram of my new project again.
Glad to create diagrams as code via this kind VS Code extension!
It's really better for me than a traditional UML Diagram.

**Comment by chialiyun** [comment]
@alanthssss happy new year and thank you for your nice words. Glad to hear that it came in useful for you.

**Comment by alanthssss** [comment]
> @alanthssss happy new year and thank you for your nice words. Glad to hear that it came in useful for you.

@chialiyun Happy new year and Thank you, too, haha.
